# -*- coding: utf-8 -*-
"""💛 Projeto V2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrmT2KHTEDh52kpFGH35slQTvpybn2jp
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

# import os
# from google.colab import userdata
#
# os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# # Instalar Framework ADK de agentes do Google ################################################
# !pip install -q google-adk

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.5-flash-preview-04-17"

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap  # Para formatar melhor a saída de texto
from IPython.display import display, Markdown  # Para exibir texto formatado no Colab
import requests  # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")


# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(
        app_name=agent.name, user_id="user1", session_id="session1"
    )
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(
        user_id="user1", session_id="session1", new_message=content
    ):
        if event.is_final_response():
            for part in event.content.parts:
                if part.text is not None:
                    final_response += part.text
                    final_response += "\n"
    return final_response


# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
    text = text.replace("•", "  *")
    return Markdown(textwrap.indent(text, "> ", predicate=lambda _: True))


##########################################
# --- Agente 1: Buscador de Notícias --- #
##########################################


def agente_buscador(area_atuacao, cliente, projeto, data_de_hoje):
    """
    Agente que busca notícias e informações relevantes sobre a área de atuação,
    o cliente e o projeto, para contextualizar o briefing de design.
    """

    buscador = Agent(
        name="agente_buscador",
        model=MODEL_ID,
        description="Agente especializado em buscar informações relevantes para briefings de design.",
        instruction=f"""
        Você é um assistente de pesquisa especializado em design.
        Sua tarefa é usar a ferramenta de busca do Google (google_search) para coletar informações relevantes
        que ajudarão a contextualizar um briefing de design.

        Você deve buscar informações sobre:
        1.  **Tendências em {area_atuacao}:**
            * Recupere as últimas notícias, artigos e estudos sobre tendências, inovações e melhores práticas em {area_atuacao}.
            * Foque em informações que possam inspirar o processo de design e ajudar a definir a direção criativa.
        2.  **Informações sobre {cliente}:**
            * Busque informações sobre a empresa {cliente}, incluindo sua história, valores, identidade visual, produtos/serviços e posicionamento no mercado.
            * Isso ajudará a garantir que o design esteja alinhado com a identidade da marca.
        3.  **Referências para o projeto {projeto}:**
            * Procure por projetos de design semelhantes a {projeto} que possam servir de inspiração ou referência.
            * Analise o que funciona bem nesses projetos e o que pode ser evitado.

        Atenção:
        * Priorize fontes confiáveis e atualizadas.
        * Seja conciso e objetivo nas suas buscas.
        * Formate a saída de forma clara e organizada, usando títulos e listas quando apropriado.
        """,
    )

    entrada_do_agente_buscador = f"""
    Área de atuação: {area_atuacao}
    Cliente: {cliente}
    Projeto: {projeto}
    Data de hoje: {data_de_hoje}
    """

    informacoes_relevantes = call_agent(buscador, entrada_do_agente_buscador)
    return informacoes_relevantes


################################################
# --- Agente 2: Analista de Insights --- #
################################################


def agente_analista(area_atuacao, cliente, projeto, informacoes_relevantes):
    """
    Agente que analisa as informações coletadas e fornece insights relevantes para o briefing.
    """

    analista = Agent(
        name="agente_analista",
        model=MODEL_ID,
        description="Agente especializado em analisar informações e fornecer insights para briefings de design.",
        tools=[],  # Este agente não precisa de ferramentas externas
        instruction=f"""
        Você é um analista de design experiente e perspicaz.
        Sua tarefa é analisar as informações fornecidas sobre a área de atuação, o cliente, o projeto
        e as informações relevantes (tendências, informações sobre o cliente, referências de projeto)
        e fornecer insights acionáveis que ajudarão a orientar o briefing e o processo de design.

        Considere os seguintes aspectos em sua análise:

        * **Tendências em {area_atuacao}:**
            * Identifique as principais tendências, inovações e melhores práticas em {area_atuacao}.
            * Analise como essas tendências podem ser aplicadas ao projeto.
            * Destaque as oportunidades e desafios relacionados a essas tendências.
        * **Informações sobre {cliente}:**
            * Analise a história, os valores, a identidade visual, os produtos/serviços e o posicionamento no mercado da empresa {cliente}.
            * Identifique como o design pode fortalecer a identidade da marca e se alinhar com seus objetivos de negócios.
            * Destaque os pontos fortes e fracos da marca em relação à concorrência.
        * **Referências para o projeto {projeto}:**
            * Analise os projetos de design semelhantes a {projeto} fornecidos como referência.
            * Identifique os elementos de design que funcionam bem e os que podem ser evitados.
            * Destaque as oportunidades de inovação e diferenciação em relação aos projetos de referência.

        Apresente sua análise de forma clara, concisa e organizada, usando títulos e listas quando apropriado.
        Forneça insights acionáveis que possam ser usados para formular perguntas de briefing mais eficazes
        e orientar as decisões de design.
        """,
    )

    entrada_do_analista = f"""
    Área de atuação: {area_atuacao}
    Cliente: {cliente}
    Projeto: {projeto}
    Informações Relevantes: {informacoes_relevantes}
    """

    analise_e_insights = call_agent(analista, entrada_do_analista)
    return analise_e_insights


################################################
# --- Agente 3: Gerador de Perguntas --- #
################################################


def agente_gerador_perguntas(area_atuacao, cliente, projeto, informacoes_relevantes):
    """
    Agente que gera perguntas detalhadas para o briefing com o cliente,
    integrando informações relevantes obtidas pelo agente_buscador.
    """

    gerador_perguntas = Agent(
        name="agente_gerador_perguntas",
        model=MODEL_ID,
        description="Agente especializado em gerar perguntas eficazes para briefings de design, considerando o contexto.",
        tools=[],  # Este agente não precisa de ferramentas externas
        instruction="""
        Você é um especialista em design e condução de briefings.
        Sua tarefa é gerar uma lista de perguntas detalhadas e eficazes para um briefing com o cliente.

        Use as informações fornecidas sobre a área de atuação, o cliente, o projeto e as informações relevantes
        para gerar perguntas que cubram todos os aspectos relevantes do projeto.

        As Informações Relevantes são muito importantes, use-as para guiar a sua geração de perguntas
        e deixe claro para o usuário que você está utilizando elas.

        Considere os seguintes tópicos ao gerar as perguntas:

        * **Objetivos do Projeto:**
            * Pergunte sobre os objetivos gerais do projeto, os resultados esperados e os indicadores de sucesso.
        * **Público-alvo:**
            * Investigue quem é o público-alvo do projeto, suas necessidades, desejos e preferências.
        * **Mensagem e Tom de Voz:**
            * Explore a mensagem que o projeto deve transmitir e o tom de voz apropriado.
        * **Concorrentes:**
            * Pergunte sobre os principais concorrentes e o que diferencia o projeto deles.
        * **Requisitos Técnicos:**
            * Averigue os requisitos técnicos, restrições e limitações do projeto.
        * **Orçamento e Cronograma:**
            * Discuta o orçamento disponível e o cronograma do projeto.
        * **Informações Relevantes:**
            * Use as informações relevantes (tendências, informações sobre o cliente, etc.) para gerar perguntas mais específicas e aprofundadas.
            * **Destaque como as informações relevantes influenciam as perguntas.**

        Formate a saída como uma lista numerada ou com marcadores.
        Seja claro, conciso e objetivo em suas perguntas.
        """,
    )

    entrada_do_gerador_perguntas = f"""
    Área de atuação: {area_atuacao}
    Cliente: {cliente}
    Projeto: {projeto}
    Informações Relevantes: {informacoes_relevantes}
    """

    perguntas_briefing = call_agent(gerador_perguntas, entrada_do_gerador_perguntas)
    return perguntas_briefing


################################################
# --- Agente 4: Apresentador/Revisor --- #
################################################


def agente_apresentador(perguntas_briefing, area_atuacao, cliente, projeto):
    """
    Agente que apresenta as perguntas do briefing ao usuário,
    permite a revisão e formata a lista final.
    """

    apresentador = Agent(
        name="agente_apresentador",
        model=MODEL_ID,
        description="Agente que apresenta, revisa e formata as perguntas do briefing.",
        tools=[],  # Este agente não precisa de ferramentas externas
        instruction="""
        Você é um assistente de design experiente em revisar e aprimorar perguntas de briefing.
        Sua tarefa é revisar a lista de perguntas fornecida e apresentar uma versão final e otimizada.

        Considere as melhores práticas para briefings de design ao revisar:
        * Tornar as perguntas mais específicas e claras.
        * Garantir que todas as áreas relevantes sejam cobertas.
        * Usar um tom adequado.
        * Evitar jargões.

        Apresente a lista final de perguntas de forma clara e organizada, usando uma lista numerada ou com marcadores.
        Não inclua explicações sobre as alterações realizadas.
        """,
    )

    entrada_do_apresentador = f"""
    Área de atuação: {area_atuacao}
    Cliente: {cliente}
    Projeto: {projeto}
    Perguntas do Briefing: {perguntas_briefing}

    Por favor, revise as perguntas e faça as alterações necessárias.
    """

    perguntas_revisadas = call_agent(apresentador, entrada_do_apresentador)
    return perguntas_revisadas


from datetime import date

print("🚀 Iniciando o Sistema de Criação de Briefing de Design com 4 Agentes 🚀")

# --- Obter as Informações Iniciais do Usuário ---
# area_atuacao()

# if opcao_fluxo == "criar":
#  cliente, projeto = obter_informacoes_projeto()  # Função para obter cliente e projeto
# else:
#  print("Funcionalidade de análise de briefing ainda não implementada.")
#  exit()

data_de_hoje = date.today().strftime("%d/%m/%Y")

# Inserir lógica do sistema de agentes ################################################

area_atuacao = input("Qual é sua área de atuação ?")
cliente = input("Qual é o seu nome?")
projeto = input("O que é o seu projeto]?")

if not (area_atuacao and cliente and projeto):
    print("Você esqueceu de fornecer alguma informação essencial!")
else:
    print(f"Maravilha! Vamos então criar o briefing para {cliente} sobre {projeto}")

    informacoes_relevantes = agente_buscador(
        area_atuacao, cliente, projeto, data_de_hoje
    )
    print("\n--- 📝 Resultado do Agente 1 (Buscador) ---\n")
    print(informacoes_relevantes)  # Substituí display(to_markdown()) por print()
    print("--------------------------------------------------------------")

    analise_e_insights = agente_analista(
        area_atuacao, cliente, projeto, informacoes_relevantes
    )
    print("\n--- 📝 Resultado do Agente 2 (Analista) ---\n")
    print(analise_e_insights)  # Substituí display(to_markdown()) por print()
    print("--------------------------------------------------------------")

    perguntas_briefing = agente_gerador_perguntas(
        area_atuacao, cliente, projeto, analise_e_insights
    )
    print("\n--- 📝 Resultado do Agente 3 (Gerador de Perguntas) ---\n")
    print(perguntas_briefing)  # Substituí display(to_markdown()) por print()
    print("--------------------------------------------------------------")

    perguntas_revisadas = agente_apresentador(
        perguntas_briefing, area_atuacao, cliente, projeto
    )
    print("\n--- 📝 Resultado do Agente 4 (Apresentador/Revisor) ---\n")
    print(perguntas_revisadas)  # Substituí display(to_markdown()) por print()
    print("--------------------------------------------------------------")

    # aexibir_ou_salvar_resultado(perguntas_revisadas, "perguntas_briefing")  # Chame a função para exibir/salvar
